language: rust
cache: cargo

rust:
  - 1.12.0
  - stable
  - beta
  - nightly

before_script:
  - if [[ "${TRAVIS_RUST_VERSION}" = "nightly" ]]; then export FEATURES="--features=unstable"; fi

script:
  - cargo build --verbose ${FEATURES}
  - RUST_BACKTRACE=1 cargo test --verbose ${FEATURES}

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly
